### ISSUE TITLE
Update the ABOUT text with the doc Dave sent

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-midwest-js#26]
Also make the changes from email below:   

In this document, can you make "The SPARROW model...." noted in the first paragraph a hyperlink to https://water.usgs.gov/nawqa/sparrow/

When you start working on the SPARROW mappers again, please update the Midwest "About-->Model Documentation" tab with the info in the attached word doc.  This new doc includes a new section "Description of the 2012 SPARROW Models for the Midwest" that provides a very brief description of what the mappers are displaying.  I've also reordered things a bit so the new section is at the top and the "SPARROW Surface Water-Quality Modeling Web Pages" goes at the bottom.  The other regions should be providing you with similar, updated model documentation docs in the near future.

Thanks,
Dave

**Comment by esmyers** [comment]
Emailed from Dave: Thu, Jul 25, 3:19 PM

**Comment by kjacobsen16** [comment]
@esmyers can you send me the word doc for this?
