### ISSUE TITLE
shut down EC2s

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-midwest-js#78]
Sparrowtest and Sparrow Prod are no longer in use and may be shut down.  We need to hang onto the sparrow10.5 Jump server though.  Any questions, pleas reach out.

**Comment by aaronstephenson** [comment]
Thanks! I just shut down the prod server in the WMA subaccount and the test server in the WIM Main account, and removed it from the auto-start list.

(side note: perhaps we could re-use the prod server for another project, and not have to ask Zno for another new instance)

**Comment by aaronstephenson** [comment]
I made a backup of the test server too, just in case.

**Comment by esmyers** [comment]
Thanks @aaronstephenson! With everything in EROS you may repurpose that prod EC2 if you have a use for it.
